server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    etag off;
    expires -1;
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";

    location = /admin {
        try_files /admin.html =404;
    }

    location /data/geojson/ {
        alias /data/geojson/;
    }

    location /indoor/ {
        alias /indoor/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
